export enum NotificationType {
  NEW_POST = 'NEW_POST',
  NEW_COMMENT = 'NEW_COMMENT',
  POST_REACTION = 'POST_REACTION',
  COMMENT_REACTION = 'COMMENT_REACTION',
  NEW_REPLY_COMMENT = 'NEW_REPLY_COMMENT', // Added for replies
  COMMUNITY_MEMBERSHIP_REQUEST = 'COMMUNITY_MEMBERSHIP_REQUEST',
  COMMUNITY_MEMBERSHIP_ACCEPTED = 'COMMUNITY_MEMBERSHIP_ACCEPTED',
  COMMUNITY_MEMBERSHIP_REJECTED = 'COMMUNITY_MEMBERSHIP_REJECTED',
  // Add other notification types as needed
}
