import {
  CommunityMembershipRequest,
  CommunityMembershipRequestStatus,
} from '../../community-membership-requests/entities/community-membership-request.entity';
import { User } from '../../users/entities/user.entity';
import { Community } from '../../communities/entities/community.entity';
import { faker } from '@faker-js/faker';

export function communityMembershipRequestFactory(
  user: User,
  community: Community,
): CommunityMembershipRequest {
  const request = new CommunityMembershipRequest();
  request.userId = user.id;
  request.communityId = community.id;
  request.user = user;
  request.community = community;
  request.status = faker.helpers.arrayElement(Object.values(CommunityMembershipRequestStatus));
  // createdAt is auto-generated by CreateDateColumn

  return request;
}
